-- APAGAR DADOS ANTIGOS
TRUNCATE TABLE public.jogos, public.palpites CASCADE;

-- INSERIR NOVOS DADOS OFICIAIS
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (1, '2026-06-11', '13:00:00', 'México', 'África do Sul', 2, 0, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (2, '2026-06-11', '20:00:00', 'Coreia do Sul', 'Tchéquia', 2, 1, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (3, '2026-06-18', '12:00:00', 'Tchéquia', 'África do Sul', NULL, NULL, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (4, '2026-06-18', '19:00:00', 'México', 'Coreia do Sul', NULL, NULL, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (5, '2026-06-24', '19:00:00', 'Tchéquia', 'México', NULL, NULL, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (6, '2026-06-24', '19:00:00', 'África do Sul', 'Coreia do Sul', NULL, NULL, 'Grupo A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (7, '2026-06-12', '15:00:00', 'Canadá', 'Bósnia e Herz.', 1, 1, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (8, '2026-06-13', '12:00:00', 'Catar', 'Suíça', 1, 1, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (9, '2026-06-18', '12:00:00', 'Suíça', 'Bósnia e Herz.', NULL, NULL, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (10, '2026-06-18', '15:00:00', 'Canadá', 'Catar', NULL, NULL, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (11, '2026-06-24', '12:00:00', 'Suíça', 'Canadá', NULL, NULL, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (12, '2026-06-24', '12:00:00', 'Bósnia e Herz.', 'Catar', NULL, NULL, 'Grupo B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (13, '2026-06-13', '18:00:00', 'Brasil', 'Marrocos', 1, 1, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (14, '2026-06-13', '21:00:00', 'Haiti', 'Escócia', 0, 1, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (15, '2026-06-19', '18:00:00', 'Escócia', 'Marrocos', NULL, NULL, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (16, '2026-06-19', '20:30:00', 'Brasil', 'Haiti', NULL, NULL, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (17, '2026-06-24', '18:00:00', 'Escócia', 'Brasil', NULL, NULL, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (18, '2026-06-24', '18:00:00', 'Marrocos', 'Haiti', NULL, NULL, 'Grupo C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (19, '2026-06-12', '18:00:00', 'EUA', 'Paraguai', 4, 1, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (20, '2026-06-13', '21:00:00', 'Australia', 'Turquia', 2, 0, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (21, '2026-06-19', '12:00:00', 'EUA', 'Australia', NULL, NULL, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (22, '2026-06-19', '20:00:00', 'Turquia', 'Paraguai', NULL, NULL, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (23, '2026-06-25', '19:00:00', 'Turquia', 'EUA', NULL, NULL, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (24, '2026-06-25', '19:00:00', 'Paraguai', 'Australia', NULL, NULL, 'Grupo D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (25, '2026-06-14', '12:00:00', 'Alemanha', 'Curaçao', 7, 1, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (26, '2026-06-14', '19:00:00', 'Costa do Marfim', 'Equador', 1, 0, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (27, '2026-06-20', '16:00:00', 'Alemanha', 'Costa do Marfim', NULL, NULL, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (28, '2026-06-20', '19:00:00', 'Equador', 'Curaçao', NULL, NULL, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (29, '2026-06-25', '16:00:00', 'Curaçao', 'Costa do Marfim', NULL, NULL, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (30, '2026-06-25', '16:00:00', 'Equador', 'Alemanha', NULL, NULL, 'Grupo E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (31, '2026-06-14', '15:00:00', 'Holanda', 'Japão', 2, 2, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (32, '2026-06-14', '20:00:00', 'Suécia', 'Tunísia', 5, 1, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (33, '2026-06-20', '12:00:00', 'Holanda', 'Suécia', NULL, NULL, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (34, '2026-06-20', '22:00:00', 'Tunísia', 'Japão', NULL, NULL, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (35, '2026-06-25', '18:00:00', 'Japão', 'Suécia', NULL, NULL, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (36, '2026-06-25', '18:00:00', 'Tunísia', 'Holanda', NULL, NULL, 'Grupo F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (37, '2026-06-15', '12:00:00', 'Bélgica', 'Egito', 1, 1, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (38, '2026-06-15', '18:00:00', 'Irã', 'Nova Zelândia', 2, 2, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (39, '2026-06-21', '12:00:00', 'Bélgica', 'Irã', NULL, NULL, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (40, '2026-06-21', '18:00:00', 'Nova Zelândia', 'Egito', NULL, NULL, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (41, '2026-06-26', '20:00:00', 'Egito', 'Irã', NULL, NULL, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (42, '2026-06-26', '20:00:00', 'Nova Zelândia', 'Bélgica', NULL, NULL, 'Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (43, '2026-06-15', '12:00:00', 'Espanha', 'Cabo Verde', 0, 0, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (44, '2026-06-15', '18:00:00', 'Arábia Saudita', 'Uruguai', 1, 1, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (45, '2026-06-21', '12:00:00', 'Espanha', 'Arábia Saudita', NULL, NULL, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (46, '2026-06-21', '18:00:00', 'Uruguai', 'Cabo Verde', NULL, NULL, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (47, '2026-06-26', '19:00:00', 'Cabo Verde', 'Arábia Saudita', NULL, NULL, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (48, '2026-06-26', '18:00:00', 'Uruguai', 'Espanha', NULL, NULL, 'Grupo H');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (49, '2026-06-16', '15:00:00', 'França', 'Senegal', 3, 1, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (50, '2026-06-16', '18:00:00', 'Iraque', 'Noruega', 1, 4, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (51, '2026-06-22', '17:00:00', 'França', 'Iraque', NULL, NULL, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (52, '2026-06-22', '20:00:00', 'Noruega', 'Senegal', NULL, NULL, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (53, '2026-06-26', '15:00:00', 'Noruega', 'França', NULL, NULL, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (54, '2026-06-26', '15:00:00', 'Senegal', 'Iraque', NULL, NULL, 'Grupo I');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (55, '2026-06-16', '20:00:00', 'Argentina', 'Argélia', 3, 0, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (56, '2026-06-16', '21:00:00', 'Austria', 'Jordânia', 3, 1, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (57, '2026-06-22', '12:00:00', 'Argentina', 'Austria', NULL, NULL, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (58, '2026-06-22', '20:00:00', 'Jordânia', 'Argélia', NULL, NULL, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (59, '2026-06-27', '21:00:00', 'Argélia', 'Austria', NULL, NULL, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (60, '2026-06-27', '21:00:00', 'Jordânia', 'Argentina', NULL, NULL, 'Grupo J');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (61, '2026-06-17', '12:00:00', 'Portugal', 'RD Congo', 1, 1, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (62, '2026-06-17', '20:00:00', 'Uzbequistão', 'Colômbia', 1, 3, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (63, '2026-06-23', '12:00:00', 'Portugal', 'Uzbequistão', NULL, NULL, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (64, '2026-06-23', '20:00:00', 'Colômbia', 'RD Congo', NULL, NULL, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (65, '2026-06-27', '19:30:00', 'Colômbia', 'Portugal', NULL, NULL, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (66, '2026-06-27', '19:30:00', 'RD Congo', 'Uzbequistão', NULL, NULL, 'Grupo K');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (67, '2026-06-17', '15:00:00', 'Inglaterra', 'Croácia', 4, 2, 'Grupo L');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (68, '2026-06-17', '19:00:00', 'Gana', 'Panama', 1, 0, 'Grupo L');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (69, '2026-06-23', '16:00:00', 'Inglaterra', 'Gana', NULL, NULL, 'Grupo L');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (70, '2026-06-23', '19:00:00', 'Panama', 'Croácia', NULL, NULL, 'Grupo L');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (71, '2026-06-27', '17:00:00', 'Panama', 'Inglaterra', NULL, NULL, 'Grupo L');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (72, '2026-06-27', '17:00:00', 'Croácia', 'Gana', NULL, NULL, 'Grupo L');
