-- EXCLUIR DADOS ANTIGOS
DELETE FROM public.palpites;
DELETE FROM public.jogos;

-- INSERIR JOGOS
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (1, '2026-06-12', '16:00:00', 'México', 'Africa', 2, 0, 'Primeira fase          GRUPO A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (2, '2026-06-12', '16:00:00', 'Canadá', 'Bósnia', 1, 1, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (3, '2026-06-13', '19:00:00', 'Brasil', 'Marrocos', 1, 1, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (4, '2026-06-12', '22:00:00', 'EUA', 'Paraguai', 4, 1, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (5, '2026-06-14', '14:00:00', 'Alemanha', 'Curaçao', 7, 1, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (6, '2026-06-14', '17:00:00', 'Holanda', 'Japão', 2, 2, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (7, '2026-06-15', '16:00:00', 'Bélgica', 'Egito', 1, 1, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (8, '2026-06-15', '13:00:00', 'Espanha', 'Cabo Verde', 0, 0, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (9, '2026-06-16', '16:00:00', 'França', 'Senegal', 3, 1, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (10, '2026-06-16', '22:00:00', 'Argentina', 'Argélia', 3, 0, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (11, '2026-06-17', '14:00:00', 'Portugal', 'RD Congo', 1, 1, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (12, '2026-06-17', '20:00:00', 'Gana', 'Panamá', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (13, '2026-06-13', '16:00:00', 'Coréa', 'Tchéquia', 2, 1, 'Primeira fase          GRUPO A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (14, '2026-06-13', '16:00:00', 'Catar', 'Suíça', 1, 1, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (15, '2026-06-13', '22:00:00', 'Haití', 'Escócia', 0, 1, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (16, '2026-06-14', '01:00:00', 'Austrália', 'Turquia', 2, 0, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (17, '2026-06-14', '20:00:00', 'Cost Marfim', 'Equador', 1, 0, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (18, '2026-06-14', '23:00:00', 'Suécia', 'Tunisia', 5, 1, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (19, '2026-06-15', '22:00:00', 'Irã', 'Nova Zelandia', 2, 2, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (20, '2026-06-15', '19:00:00', 'Arab Saudita', 'Uruguai', 1, 1, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (21, '2026-06-16', '19:00:00', 'Iraque', 'Noruega', 1, 4, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (22, '2026-06-17', '01:00:00', 'Austria', 'Jordania', 3, 1, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (23, '2026-06-17', '23:00:00', 'Colômbia', 'Uzbequistão', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (24, '2026-06-17', '17:00:00', 'Inglaterra', 'Croácia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (25, '2026-06-18', '19:00:00', 'Tchéquia', 'Africa', NULL, NULL, 'Primeira fase          GRUPO A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (26, '2026-06-18', '19:00:00', 'Canadá', 'Catar', NULL, NULL, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (27, '2026-06-19', '21:30:00', 'Brasil', 'Haití', NULL, NULL, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (28, '2026-06-19', '16:00:00', 'EUA', 'Austrália', NULL, NULL, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (29, '2026-06-20', '17:00:00', 'Alemanha', 'Cost Marfim', NULL, NULL, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (30, '2026-06-20', '14:00:00', 'Holanda', 'Suécia', NULL, NULL, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (31, '2026-06-21', '16:00:00', 'Bélgica', 'Irã', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (32, '2026-06-21', '13:00:00', 'Espanha', 'Arábia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (33, '2026-06-22', '18:00:00', 'França', 'Iraque', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (34, '2026-06-22', '14:00:00', 'Argentina', 'Aústria', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (35, '2026-06-23', '14:00:00', 'Portugal', 'Uzbequistão', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (36, '2026-06-23', '20:00:00', 'Panamá', 'Croácia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (37, '2026-06-18', '16:00:00', 'México', 'Coréa', NULL, NULL, 'Primeira fase          GRUPO A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (38, '2026-06-18', '16:00:00', 'Suíça', 'Bósnia', NULL, NULL, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (39, '2026-06-19', '19:00:00', 'Escócia', 'Marrocos', NULL, NULL, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (40, '2026-06-20', '01:00:00', 'Turquia', 'Paraguai', NULL, NULL, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (41, '2026-06-20', '21:00:00', 'Equador', 'Curaçao', NULL, NULL, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (42, '2026-06-21', '01:00:00', 'Tunisia', 'Japão', NULL, NULL, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (43, '2026-06-21', '22:00:00', 'Nova Zelandia', 'Egito', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (44, '2026-06-21', '19:00:00', 'Uruguai', 'Cabo verde', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (45, '2026-06-22', '21:00:00', 'Noroega', 'Senegal', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (46, '2026-06-23', '00:00:00', 'Jordania', 'Argélia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (47, '2026-06-23', '23:00:00', 'Colômbia', 'RD Congo', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (48, '2026-06-23', '17:00:00', 'Inglaterra', 'Gana', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (49, '2026-06-24', '16:00:00', 'Tchéquia', 'México', NULL, NULL, 'Primeira fase          GRUPO A');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (50, '2026-06-24', '16:00:00', 'Suíça', 'Canadá', NULL, NULL, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (51, '2026-06-24', '19:00:00', 'Marrocos', 'Haití', NULL, NULL, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (52, '2026-06-25', '23:00:00', 'Turquia', 'EUA', NULL, NULL, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (53, '2026-06-25', '17:00:00', 'Curaçao', 'Cost Marfim', NULL, NULL, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (54, '2026-06-25', '20:00:00', 'Japão', 'Suécia', NULL, NULL, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (55, '2026-06-27', '00:00:00', 'Egito', 'Irã', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (56, '2026-06-26', '21:00:00', 'Uruguai', 'Espanha', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (57, '2026-06-26', '16:00:00', 'Noroega', 'França', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (58, '2026-06-27', '23:00:00', 'Argélia', 'Aústria', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (59, '2026-06-27', '20:30:00', 'Colômbia', 'Portugal', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (60, '2026-06-27', '18:00:00', 'Croácia', 'Gana', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (61, '2026-06-24', '16:00:00', 'Africa', 'Corea', NULL, NULL, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (62, '2026-06-24', '16:00:00', 'Bósnia', 'Catar', NULL, NULL, 'Primeira fase          GRUPO B');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (63, '2026-06-24', '19:00:00', 'Escócia', 'Brasil', NULL, NULL, 'Primeira fase          GRUPO C');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (64, '2026-06-25', '23:00:00', 'Paraguai', 'Austrália', NULL, NULL, 'Primeira fase          GRUPO D');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (65, '2026-06-25', '17:00:00', 'Equador', 'Alemanha', NULL, NULL, 'Primeira fase          GRUPO E');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (66, '2026-06-25', '20:00:00', 'Tunisia', 'Holanda', NULL, NULL, 'Primeira fase          GRUPO F');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (67, '2026-06-27', '00:00:00', 'Bélgica', 'Nova Zelandia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (68, '2026-06-26', '21:00:00', 'Cabo', 'Arábia', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (69, '2026-06-26', '16:00:00', 'Senegal', 'Iraque', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (70, '2026-06-27', '23:00:00', 'Jordania', 'Argentina', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (71, '2026-06-27', '20:30:00', 'RD Congo', 'Uzbequistão', NULL, NULL, 'Primeira fase          Grupo G');
INSERT INTO public.jogos (id, data, hora, time_casa, time_fora, gols_casa_real, gols_fora_real, grupo) VALUES (72, '2026-06-27', '18:00:00', 'Panamá', 'Inglaterra', NULL, NULL, 'Primeira fase          Grupo G');

-- INSERIR PALPITES
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Aline', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Eduardo', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Silvio', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (1, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Aline', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Eduardo', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Silvio', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (2, 'Daniel', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Eduardo', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Silvio', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (3, 'Daniel', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Matheus', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Eduardo', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (4, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Aline', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Eduardo', 6, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Silvio', 5, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (5, 'Daniel', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Matheus', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Eduardo', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Silvio', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (6, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Eduardo', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Silvio', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (7, 'Daniel', 3, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Aline', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Eduardo', 7, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Silvio', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (8, 'Daniel', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Aline', 5, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Matheus', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Eduardo', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Silvio', 3, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (9, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Aline', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Eduardo', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Sidney', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (10, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Aline', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Eduardo', 4, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (11, 'Daniel', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Aline', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Matheus', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Eduardo', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (12, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Aline', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Matheus', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Eduardo', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (13, 'Daniel', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Aline', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Matheus', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Eduardo', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Sidney', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Silvio', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (14, 'Daniel', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Aline', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Matheus', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Eduardo', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Sidney', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Silvio', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (15, 'Daniel', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Aline', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Matheus', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Eduardo', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Silvio', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (16, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Aline', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Matheus', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Eduardo', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Silvio', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (17, 'Daniel', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Eduardo', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Silvio', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (18, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Matheus', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Eduardo', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Sidney', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (19, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Aline', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Matheus', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Eduardo', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Sidney', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Silvio', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (20, 'Daniel', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Aline', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Matheus', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Eduardo', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Silvio', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (21, 'Daniel', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Eduardo', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Sidney', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (22, 'Daniel', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Eduardo', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (23, 'Daniel', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Matheus', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Eduardo', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Silvio', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (24, 'Daniel', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Aline', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Matheus', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Eduardo', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (25, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Eduardo', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Sidney', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Silvio', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (26, 'Daniel', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Aline', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Eduardo', 5, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Sidney', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (27, 'Daniel', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Eduardo', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (28, 'Daniel', 3, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Aline', 4, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Eduardo', 4, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Silvio', 5, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (29, 'Daniel', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Eduardo', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Sidney', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Silvio', 3, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (30, 'Daniel', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Aline', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Eduardo', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (31, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Aline', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Eduardo', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Sidney', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (32, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Aline', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Eduardo', 5, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Sidney', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Silvio', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (33, 'Daniel', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Eduardo', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Silvio', 4, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (34, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Aline', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Eduardo', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Sidney', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Silvio', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (35, 'Daniel', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Aline', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Matheus', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Eduardo', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Silvio', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (36, 'Daniel', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Matheus', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Eduardo', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Silvio', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (37, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Matheus', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Eduardo', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Sidney', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Silvio', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (38, 'Daniel', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Aline', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Matheus', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Eduardo', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Sidney', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Silvio', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (39, 'Daniel', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Matheus', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Eduardo', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Silvio', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (40, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Aline', 4, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Eduardo', 6, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Silvio', 3, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (41, 'Daniel', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Aline', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Matheus', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Eduardo', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Silvio', 0, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (42, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Aline', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Matheus', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Eduardo', 0, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Sidney', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Silvio', 3, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (43, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Aline', 1, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Matheus', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Eduardo', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (44, 'Daniel', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Aline', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Matheus', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Eduardo', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Sidney', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Silvio', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (45, 'Daniel', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Aline', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Matheus', 1, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Eduardo', 1, 3);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Sidney', 2, 2);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Silvio', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (46, 'Daniel', 0, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Matheus', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Eduardo', 5, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Sidney', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Silvio', 4, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (47, 'Daniel', 3, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Aline', 2, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Matheus', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Eduardo', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Sidney', 3, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Silvio', 2, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (48, 'Daniel', 1, 1);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Aline', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Matheus', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Eduardo', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Sidney', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Silvio', 0, 0);
INSERT INTO public.palpites (jogo_id, jogador_nome, palpite_casa, palpite_fora) VALUES (72, 'Daniel', 0, 0);
